// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      throw UnsupportedError(
        'DefaultFirebaseOptions have not been configured for web - '
        'you can reconfigure this by running the FlutterFire CLI again.',
      );
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBGh8sdV28W92JndrUHQfc4G9pGNPvMFVI',
    appId: '1:1024895323281:android:459358f77581b71507c330',
    messagingSenderId: '1024895323281',
    projectId: 'donorsync-36fa8',
    storageBucket: 'donorsync-36fa8.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAEJ6YhcoRurat5yp7x6G0rI9wXzjInyjg',
    appId: '1:1024895323281:ios:016b3f21f7c9cb7e07c330',
    messagingSenderId: '1024895323281',
    projectId: 'donorsync-36fa8',
    storageBucket: 'donorsync-36fa8.firebasestorage.app',
    androidClientId: '1024895323281-t834frpujpbiv6dtqph26cekkq878cq1.apps.googleusercontent.com',
    iosClientId: '1024895323281-0cccr4lmu81ifo89ovung3glhdtmll5d.apps.googleusercontent.com',
    iosBundleId: 'com.example.donorSync',
  );
}
